import type { WorldCupImageAsset } from "@/lib/world-cup-image-assets";

export const worldCupImageAssets: WorldCupImageAsset[] = [
  {
    id: "flopass3-e5ebe8bf",
    src: "/daily-images/commons/flopass3-e5ebe8bf.jpg",
    title: "1998: Flopass3",
    alt: "Arkivbilde fra 1998: Flopass3",
    caption: "Arkivbilde fra 1998-sporet i VM-arkivet: Flopass3.",
    context: "Norsk VM-nostalgi trenger ikke gullramme: en lang ball, en høy spiss og et Brasil som plutselig måtte se seg over skulderen.",
    facts: ["Tore André Flo utlignet mot Brasil i 1998.","Norge vant kampen 2-1.","Seieren sendte Norge til åttedelsfinale."],
    credit: "Enriquecardova at English Wikipedia",
    license: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Flopass3.jpg",
    approved: true,
    mediaType: "photo",
    year: "1998",
    teams: ["Norway","Brazil"],
    matchIds: [],
    momentIds: ["norway-return-2026"],
    tags: ["1998","norway","brazil","flo","diagram","photo","commons"],
    orientation: "portrait",
    focus: "center",
  },
  {
    id: "bergkampscore3-e97db9ac",
    src: "/daily-images/commons/bergkampscore3-e97db9ac.jpg",
    title: "1998: Bergkampscore3",
    alt: "Arkivbilde fra 1998: Bergkampscore3",
    caption: "Arkivbilde fra 1998-sporet i VM-arkivet: Bergkampscore3.",
    context: "Bergkamp-målet er VM som tavlekunst: ett oppspill, én førsteberøring og en avslutning som fortsatt gir langballen et bedre rykte.",
    facts: ["Nederland slo Argentina 2-1 i kvartfinalen.","Dennis Bergkamp scoret vinnermålet.","Målet kom etter en lang pasning fra Frank de Boer."],
    credit: "Enriquecardova at English Wikipedia",
    license: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bergkampscore3.jpg",
    approved: true,
    mediaType: "photo",
    year: "1998",
    teams: ["Netherlands","Argentina"],
    matchIds: [],
    momentIds: ["bergkamp-1998"],
    tags: ["1998","netherlands","argentina","bergkamp","diagram","photo","commons"],
    orientation: "portrait",
    focus: "center",
  },
  {
    id: "argentina-en-el-mundial-1930-los-sports-1930-08-08-387-98fe54bb",
    src: "/daily-images/commons/argentina-en-el-mundial-1930-los-sports-1930-08-08-387-98fe54bb.jpg",
    title: "1930: Argentina en el Mundial 1930, Los Sports, 1930-08-08 (387)",
    alt: "Arkivbilde fra 1930: Argentina en el Mundial 1930, Los Sports, 1930-08-08 (387)",
    caption: "Arkivbilde fra 1930-sporet i VM-arkivet: Argentina en el Mundial 1930, Los Sports, 1930-08-08 (387).",
    context: "Den første VM-finalen gjør arkivet fysisk: korte bukser, lang reise og et mesterskap som ennå ikke visste at det skulle bli en verdenskalender.",
    facts: ["Uruguay slo Argentina 4-2 i finalen.","Finalen ble spilt på Estadio Centenario i Montevideo.","1930-VM hadde bare 13 lag."],
    credit: "Unknown author",
    license: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Argentina%20en%20el%20Mundial%201930%2C%20Los%20Sports%2C%201930-08-08%20(387).jpg",
    approved: true,
    mediaType: "photo",
    year: "1930",
    teams: ["Uruguay","Argentina"],
    matchIds: [],
    momentIds: ["uruguay-1930"],
    tags: ["1930","final","uruguay","argentina","rimet","early-world-cup","photo","commons"],
    orientation: "landscape",
    focus: "center",
  },
  {
    id: "ademir-de-menezes-1950-1a40d7bd",
    src: "/daily-images/commons/ademir-de-menezes-1950-1a40d7bd.jpg",
    title: "1950: Ademir de Menezes (1950)",
    alt: "Arkivbilde fra 1950: Ademir de Menezes (1950)",
    caption: "Arkivbilde fra 1950-sporet i VM-arkivet: Ademir de Menezes (1950).",
    context: "1950-bildene bærer VM-historiens mest berømte stillhet: Brasil var vert, favoritt og nesten kronet før Uruguay snudde rommet.",
    facts: ["Uruguay vant den avgjørende finalerundekampen 2-1.","Maracanazo er fortsatt Brasils åpne VM-sår.","1950 hadde finalerunde i stedet for vanlig finale."],
    credit: "Unknown author",
    license: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Ademir%20de%20Menezes%20(1950).jpg",
    approved: true,
    mediaType: "photo",
    year: "1950",
    teams: ["Brazil","Uruguay"],
    matchIds: [],
    momentIds: ["maracanazo-1950"],
    tags: ["1950","brazil","uruguay","maracanazo","archive","photo","commons"],
    orientation: "portrait",
    focus: "center",
  },
  {
    id: "alemania-v-hungria-estadio-1954-07-17-583-01-0ac79dca",
    src: "/daily-images/commons/alemania-v-hungria-estadio-1954-07-17-583-01-0ac79dca.jpg",
    title: "1954: Alemania v Hungría, Estadio, 1954-07-17 (583) 01",
    alt: "Arkivbilde fra 1954: Alemania v Hungría, Estadio, 1954-07-17 (583) 01",
    caption: "Arkivbilde fra 1954-sporet i VM-arkivet: Alemania v Hungría, Estadio, 1954-07-17 (583) 01.",
    context: "Bern-finalen er et arkivskap for alle som liker favoritter, regnvær og den typen resultat som gjør at folk endrer tonefall.",
    facts: ["Vest-Tyskland slo Ungarn 3-2.","Kampen er kjent som Mirakelet i Bern.","Ungarn hadde slått Vest-Tyskland 8-3 tidligere i turneringen."],
    credit: "Unknown author",
    license: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Alemania%20v%20Hungr%C3%ADa%2C%20Estadio%2C%201954-07-17%20(583)%2001.jpg",
    approved: true,
    mediaType: "photo",
    year: "1954",
    teams: ["Germany","Hungary"],
    matchIds: [],
    momentIds: ["germany-2014"],
    tags: ["1954","germany","hungary","final","miracle-of-bern","photo","commons"],
    orientation: "landscape",
    focus: "center",
  },
  {
    id: "brazil-v-italia-1970-01-cbe19ee7",
    src: "/daily-images/commons/brazil-v-italia-1970-01-cbe19ee7.jpg",
    title: "1970: Brazil v italia 1970 01",
    alt: "Arkivbilde fra 1970: Brazil v italia 1970 01",
    caption: "Arkivbilde fra 1970-sporet i VM-arkivet: Brazil v italia 1970 01.",
    context: "Mexico 1970 er den vakre standarden alle Brasil-tips later som de har regnet seg frem til, selv når de egentlig bare savner Pelé.",
    facts: ["Brasil slo Italia 4-1 i finalen.","Pelé ble første spiller med tre VM-gull.","Carlos Albertos finalemål er fortsatt taktisk museumsstoff."],
    credit: "Unknown author",
    license: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Brazil%20v%20italia%201970%2001.jpg",
    approved: true,
    mediaType: "photo",
    year: "1970",
    teams: ["Brazil","Italy"],
    matchIds: [],
    momentIds: ["brazil-1970"],
    tags: ["1970","brazil","italy","final","pele","photo","commons"],
    orientation: "landscape",
    focus: "center",
  },
  {
    id: "ausschnitt-mildred-scheel-83e23c6b",
    src: "/daily-images/commons/ausschnitt-mildred-scheel-83e23c6b.jpg",
    title: "1974: Ausschnitt Mildred Scheel",
    alt: "Arkivbilde fra 1974: Ausschnitt Mildred Scheel",
    caption: "Arkivbilde fra 1974-sporet i VM-arkivet: Ausschnitt Mildred Scheel.",
    context: "1974-finalen er totalfotballens store rettssak: Nederland hadde idéen, Vest-Tyskland hadde pokalen og kjelleren har fortsatt meninger.",
    facts: ["Vest-Tyskland slo Nederland 2-1.","Nederland tok ledelsen før tysk spiller hadde rørt ballen.","Cruyff-generasjonen ble stil uten gull."],
    credit: "Bert Verhoeff / Anefo",
    license: "CC0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Ausschnitt%20Mildred%20Scheel.jpg",
    approved: true,
    mediaType: "photo",
    year: "1974",
    teams: ["Germany","Netherlands"],
    matchIds: [],
    momentIds: ["netherlands-brazil-1998"],
    tags: ["1974","germany","netherlands","cruyff","total-football","final","photo","commons"],
    orientation: "portrait",
    focus: "center",
  },
  {
    id: "abrazo-alma-todos-a304a2f8",
    src: "/daily-images/commons/abrazo-alma-todos-a304a2f8.jpg",
    title: "1978: Abrazo alma todos",
    alt: "Arkivbilde fra 1978: Abrazo alma todos",
    caption: "Arkivbilde fra 1978-sporet i VM-arkivet: Abrazo alma todos.",
    context: "Buenos Aires-finalen har alt et privat VM-arkiv liker: konfetti, trykk, ekstraomganger og en vertsnasjon som gjorde kvelden enorm.",
    facts: ["Argentina slo Nederland 3-1 etter ekstraomganger.","Mario Kempes scoret to mål i finalen.","Nederland tapte sin andre strake VM-finale."],
    credit: "Ricardo Alfieri",
    license: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Abrazo%20alma%20todos.jpg",
    approved: true,
    mediaType: "photo",
    year: "1978",
    teams: ["Argentina","Netherlands"],
    matchIds: [],
    momentIds: ["bergkamp-1998"],
    tags: ["1978","argentina","netherlands","final","kempes","photo","commons"],
    orientation: "landscape",
    focus: "center",
  },
  {
    id: "arg-frg-1986-06-29-d25bb68f",
    src: "/daily-images/commons/arg-frg-1986-06-29-d25bb68f.png",
    title: "1986: ARG-FRG 1986-06-29",
    alt: "Diagram fra 1986: ARG-FRG 1986-06-29",
    caption: "Diagram/oppstilling fra 1986-arkivet: ARG-FRG 1986-06-29.",
    context: "1986-finalen er Maradona-turneringen med sluttstrek: Argentina hadde nerven, Vest-Tyskland hadde opphentingen, og Burruchaga hadde siste løp.",
    facts: ["Argentina slo Vest-Tyskland 3-2.","Burruchaga avgjorde finalen sent.","Maradona var turneringens gravitasjonssenter."],
    credit: "Zotteteen1",
    license: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:ARG-FRG%201986-06-29.svg",
    approved: true,
    mediaType: "diagram",
    year: "1986",
    teams: ["Argentina","Germany"],
    matchIds: [],
    momentIds: ["maradona-1986"],
    tags: ["1986","argentina","germany","maradona","final","diagram","commons"],
    orientation: "portrait",
    focus: "center",
  },
  {
    id: "2006-fifa-world-cup-italy-buffon-materazzi-and-perrott-6b259833",
    src: "/daily-images/commons/2006-fifa-world-cup-italy-buffon-materazzi-and-perrott-6b259833.jpg",
    title: "2006: 2006 VM - Italy - Buffon, Materazzi and Perrotta (edited)",
    alt: "Arkivbilde fra 2006: 2006 FIFA World Cup - Italy - Buffon, Materazzi and Perrotta (edited)",
    caption: "Arkivbilde fra 2006-sporet i VM-arkivet: 2006 FIFA World Cup - Italy - Buffon, Materazzi and Perrotta (edited).",
    context: "Berlin 2006 er finalen som minner alle om at VM-historie ofte skrives etter 120 minutter og med litt for mye puls.",
    facts: ["Italia slo Frankrike på straffer.","Kampen endte 1-1 etter ekstraomganger.","Zidane spilte sin siste landskamp."],
    credit: "Original: Olaf Nordwich Derivative work: Danyele",
    license: "CC BY-SA 2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2006%20FIFA%20World%20Cup%20-%20Italy%20-%20Buffon%2C%20Materazzi%20and%20Perrotta%20(edited).jpg",
    approved: true,
    mediaType: "photo",
    year: "2006",
    teams: ["Italy","France"],
    matchIds: [],
    momentIds: ["baggio-1994","france-1998"],
    tags: ["2006","italy","france","final","penalties","zidane","photo","commons"],
    orientation: "portrait",
    focus: "center",
  },
  {
    id: "2010-fifa-world-cup-spain-with-cup-85615f44",
    src: "/daily-images/commons/2010-fifa-world-cup-spain-with-cup-85615f44.jpg",
    title: "2010: 2010 VM Spain with cup",
    alt: "Arkivbilde fra 2010: 2010 FIFA World Cup Spain with cup",
    caption: "Arkivbilde fra 2010-sporet i VM-arkivet: 2010 FIFA World Cup Spain with cup.",
    context: "2010-finalen er den lave scorens høymesse: Spania trillet, Nederland taklet, og Iniesta skrev punktum da rommet nesten hadde gitt opp.",
    facts: ["Spania slo Nederland 1-0 etter ekstraomganger.","Iniesta scoret finalens eneste mål.","Dette var Spanias første VM-gull."],
    credit: "Christophe Badoux",
    license: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2010%20FIFA%20World%20Cup%20Spain%20with%20cup.JPG",
    approved: true,
    mediaType: "photo",
    year: "2010",
    teams: ["Spain","Netherlands"],
    matchIds: [],
    momentIds: ["spain-2010"],
    tags: ["2010","spain","netherlands","final","iniesta","photo","commons"],
    orientation: "landscape",
    focus: "center",
  },
  {
    id: "2026-fifa-world-cup-federal-interagency-coordination-p-52e805dc",
    src: "/daily-images/commons/2026-fifa-world-cup-federal-interagency-coordination-p-52e805dc.jpg",
    title: "2026: 2026 VM Federal Interagency Coordination Plan (55118098...",
    alt: "Arkivbilde fra 2026: 2026 FIFA World Cup Federal Interagency Coordination Plan (55118098627)",
    caption: "Arkivbilde fra 2026-sporet i VM-arkivet: 2026 FIFA World Cup Federal Interagency Coordination Plan (55118098627).",
    context: "2026-bildene handler om skala: tre vertsland, 48 lag og en turnering som gjør selv den ryddigste notatblokka litt nervøs.",
    facts: ["2026 blir første VM med 48 lag.","USA, Canada og Mexico deler vertskapet.","Turneringen får 104 kamper."],
    credit: "DHSgov",
    license: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2026%20FIFA%20World%20Cup%20Federal%20Interagency%20Coordination%20Plan%20(55118098627).jpg",
    approved: true,
    mediaType: "photo",
    year: "2026",
    teams: ["USA"],
    matchIds: [],
    momentIds: ["world-cup-2026-format"],
    tags: ["2026","usa","host","venue","format","photo","commons"],
    orientation: "landscape",
    focus: "center",
  },
  {
    id: "argentina-lineup-v-uruguay-1930-5839c4aa",
    src: "/daily-images/commons/argentina-lineup-v-uruguay-1930-5839c4aa.jpg",
    title: "1930: Argentina lineup v uruguay 1930",
    alt: "Diagram fra 1930: Argentina lineup v uruguay 1930",
    caption: "Diagram/oppstilling fra 1930-arkivet: Argentina lineup v uruguay 1930.",
    context: "Den første VM-finalen gjør arkivet fysisk: korte bukser, lang reise og et mesterskap som ennå ikke visste at det skulle bli en verdenskalender.",
    facts: ["Uruguay slo Argentina 4-2 i finalen.","Finalen ble spilt på Estadio Centenario i Montevideo.","1930-VM hadde bare 13 lag."],
    credit: "Unknown author",
    license: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Argentina%20lineup%20v%20uruguay%201930.jpg",
    approved: true,
    mediaType: "diagram",
    year: "1930",
    teams: ["Uruguay","Argentina"],
    matchIds: [],
    momentIds: ["uruguay-1930"],
    tags: ["1930","final","uruguay","argentina","rimet","early-world-cup","diagram","commons"],
    orientation: "landscape",
    focus: "center",
  },
  {
    id: "alemania-v-hungria-estadio-1954-07-17-583-02-c9ae481f",
    src: "/daily-images/commons/alemania-v-hungria-estadio-1954-07-17-583-02-c9ae481f.jpg",
    title: "1954: Alemania v Hungría, Estadio, 1954-07-17 (583) 02",
    alt: "Arkivbilde fra 1954: Alemania v Hungría, Estadio, 1954-07-17 (583) 02",
    caption: "Arkivbilde fra 1954-sporet i VM-arkivet: Alemania v Hungría, Estadio, 1954-07-17 (583) 02.",
    context: "Bern-finalen er et arkivskap for alle som liker favoritter, regnvær og den typen resultat som gjør at folk endrer tonefall.",
    facts: ["Vest-Tyskland slo Ungarn 3-2.","Kampen er kjent som Mirakelet i Bern.","Ungarn hadde slått Vest-Tyskland 8-3 tidligere i turneringen."],
    credit: "Unknown author",
    license: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Alemania%20v%20Hungr%C3%ADa%2C%20Estadio%2C%201954-07-17%20(583)%2002.jpg",
    approved: true,
    mediaType: "photo",
    year: "1954",
    teams: ["Germany","Hungary"],
    matchIds: [],
    momentIds: ["germany-2014"],
    tags: ["1954","germany","hungary","final","miracle-of-bern","photo","commons"],
    orientation: "landscape",
    focus: "center",
  },
  {
    id: "brazil-v-italia-1970-02-d2dd62e4",
    src: "/daily-images/commons/brazil-v-italia-1970-02-d2dd62e4.jpg",
    title: "1970: Brazil v italia 1970 02",
    alt: "Arkivbilde fra 1970: Brazil v italia 1970 02",
    caption: "Arkivbilde fra 1970-sporet i VM-arkivet: Brazil v italia 1970 02.",
    context: "Mexico 1970 er den vakre standarden alle Brasil-tips later som de har regnet seg frem til, selv når de egentlig bare savner Pelé.",
    facts: ["Brasil slo Italia 4-1 i finalen.","Pelé ble første spiller med tre VM-gull.","Carlos Albertos finalemål er fortsatt taktisk museumsstoff."],
    credit: "Unknown author",
    license: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Brazil%20v%20italia%201970%2002.jpg",
    approved: true,
    mediaType: "photo",
    year: "1970",
    teams: ["Brazil","Italy"],
    matchIds: [],
    momentIds: ["brazil-1970"],
    tags: ["1970","brazil","italy","final","pele","photo","commons"],
    orientation: "landscape",
    focus: "center",
  },
  {
    id: "beckenbauer-cruyff-alfieri-42a25afc",
    src: "/daily-images/commons/beckenbauer-cruyff-alfieri-42a25afc.jpg",
    title: "1974: Beckenbauer cruyff alfieri",
    alt: "Arkivbilde fra 1974: Beckenbauer cruyff alfieri",
    caption: "Arkivbilde fra 1974-sporet i VM-arkivet: Beckenbauer cruyff alfieri.",
    context: "1974-finalen er totalfotballens store rettssak: Nederland hadde idéen, Vest-Tyskland hadde pokalen og kjelleren har fortsatt meninger.",
    facts: ["Vest-Tyskland slo Nederland 2-1.","Nederland tok ledelsen før tysk spiller hadde rørt ballen.","Cruyff-generasjonen ble stil uten gull."],
    credit: "Ricardo Alfieri",
    license: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Beckenbauer%20cruyff%20alfieri.jpg",
    approved: true,
    mediaType: "photo",
    year: "1974",
    teams: ["Germany","Netherlands"],
    matchIds: [],
    momentIds: ["netherlands-brazil-1998"],
    tags: ["1974","germany","netherlands","cruyff","total-football","final","photo","commons"],
    orientation: "landscape",
    focus: "center",
  },
  {
    id: "arg-ger-1986-06-29-ar-8a2a84cb",
    src: "/daily-images/commons/arg-ger-1986-06-29-ar-8a2a84cb.png",
    title: "1986: ARG-GER 1986-06-29-ar",
    alt: "Diagram fra 1986: ARG-GER 1986-06-29-ar",
    caption: "Diagram/oppstilling fra 1986-arkivet: ARG-GER 1986-06-29-ar.",
    context: "1986-finalen er Maradona-turneringen med sluttstrek: Argentina hadde nerven, Vest-Tyskland hadde opphentingen, og Burruchaga hadde siste løp.",
    facts: ["Argentina slo Vest-Tyskland 3-2.","Burruchaga avgjorde finalen sent.","Maradona var turneringens gravitasjonssenter."],
    credit: "Original: Zotteteen1 Derivative: باسم",
    license: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:ARG-GER%201986-06-29-ar.svg",
    approved: true,
    mediaType: "diagram",
    year: "1986",
    teams: ["Argentina","Germany"],
    matchIds: [],
    momentIds: ["maradona-1986"],
    tags: ["1986","argentina","germany","maradona","final","diagram","commons"],
    orientation: "portrait",
    focus: "center",
  },
  {
    id: "2006-07-09-italy-france-line-up-el-c489e06e",
    src: "/daily-images/commons/2006-07-09-italy-france-line-up-el-c489e06e.png",
    title: "2006: 2006-07-09 Italy-France line-up el",
    alt: "Diagram fra 2006: 2006-07-09 Italy-France line-up el",
    caption: "Diagram/oppstilling fra 2006-arkivet: 2006-07-09 Italy-France line-up el.",
    context: "Berlin 2006 er finalen som minner alle om at VM-historie ofte skrives etter 120 minutter og med litt for mye puls.",
    facts: ["Italia slo Frankrike på straffer.","Kampen endte 1-1 etter ekstraomganger.","Zidane spilte sin siste landskamp."],
    credit: "Αντιγόνη",
    license: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2006-07-09%20Italy-France%20line-up%20el.svg",
    approved: true,
    mediaType: "diagram",
    year: "2006",
    teams: ["Italy","France"],
    matchIds: [],
    momentIds: ["baggio-1994","france-1998"],
    tags: ["2006","italy","france","final","penalties","zidane","diagram","commons"],
    orientation: "portrait",
    focus: "center",
  },
  {
    id: "2010-world-cup-spain-with-cup-29047488",
    src: "/daily-images/commons/2010-world-cup-spain-with-cup-29047488.jpg",
    title: "2010: 2010 VM Spain with cup",
    alt: "Arkivbilde fra 2010: 2010 World Cup Spain with cup",
    caption: "Arkivbilde fra 2010-sporet i VM-arkivet: 2010 World Cup Spain with cup.",
    context: "2010-finalen er den lave scorens høymesse: Spania trillet, Nederland taklet, og Iniesta skrev punktum da rommet nesten hadde gitt opp.",
    facts: ["Spania slo Nederland 1-0 etter ekstraomganger.","Iniesta scoret finalens eneste mål.","Dette var Spanias første VM-gull."],
    credit: "Christophe Badoux",
    license: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2010%20World%20Cup%20Spain%20with%20cup.JPG",
    approved: true,
    mediaType: "photo",
    year: "2010",
    teams: ["Spain","Netherlands"],
    matchIds: [],
    momentIds: ["spain-2010"],
    tags: ["2010","spain","netherlands","final","iniesta","photo","commons"],
    orientation: "landscape",
    focus: "center",
  },
  {
    id: "2026-fifa-world-cup-federal-interagency-coordination-p-d8bc48d9",
    src: "/daily-images/commons/2026-fifa-world-cup-federal-interagency-coordination-p-d8bc48d9.jpg",
    title: "2026: 2026 VM Federal Interagency Coordination Plan (55118098...",
    alt: "Arkivbilde fra 2026: 2026 FIFA World Cup Federal Interagency Coordination Plan (55118098732)",
    caption: "Arkivbilde fra 2026-sporet i VM-arkivet: 2026 FIFA World Cup Federal Interagency Coordination Plan (55118098732).",
    context: "2026-bildene handler om skala: tre vertsland, 48 lag og en turnering som gjør selv den ryddigste notatblokka litt nervøs.",
    facts: ["2026 blir første VM med 48 lag.","USA, Canada og Mexico deler vertskapet.","Turneringen får 104 kamper."],
    credit: "DHSgov",
    license: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2026%20FIFA%20World%20Cup%20Federal%20Interagency%20Coordination%20Plan%20(55118098732).jpg",
    approved: true,
    mediaType: "photo",
    year: "2026",
    teams: ["USA"],
    matchIds: [],
    momentIds: ["world-cup-2026-format"],
    tags: ["2026","usa","host","venue","format","photo","commons"],
    orientation: "landscape",
    focus: "center",
  },
  {
    id: "dorado-gol-uruguay-a812f46c",
    src: "/daily-images/commons/dorado-gol-uruguay-a812f46c.jpg",
    title: "1930: Dorado gol uruguay",
    alt: "Arkivbilde fra 1930: Dorado gol uruguay",
    caption: "Arkivbilde fra 1930-sporet i VM-arkivet: Dorado gol uruguay.",
    context: "Den første VM-finalen gjør arkivet fysisk: korte bukser, lang reise og et mesterskap som ennå ikke visste at det skulle bli en verdenskalender.",
    facts: ["Uruguay slo Argentina 4-2 i finalen.","Finalen ble spilt på Estadio Centenario i Montevideo.","1930-VM hadde bare 13 lag."],
    credit: "Unknown author",
    license: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Dorado%20gol%20uruguay.jpg",
    approved: true,
    mediaType: "photo",
    year: "1930",
    teams: ["Uruguay","Argentina"],
    matchIds: [],
    momentIds: ["uruguay-1930"],
    tags: ["1930","final","uruguay","argentina","rimet","early-world-cup","photo","commons"],
    orientation: "landscape",
    focus: "center",
  },
  {
    id: "ademir-de-menezes-estadio-1950-08-05-377-45b75777",
    src: "/daily-images/commons/ademir-de-menezes-estadio-1950-08-05-377-45b75777.jpg",
    title: "1950: Ademir de Menezes, Estadio, 1950-08-05 (377)",
    alt: "Arkivbilde fra 1950: Ademir de Menezes, Estadio, 1950-08-05 (377)",
    caption: "Arkivbilde fra 1950-sporet i VM-arkivet: Ademir de Menezes, Estadio, 1950-08-05 (377).",
    context: "1950-bildene bærer VM-historiens mest berømte stillhet: Brasil var vert, favoritt og nesten kronet før Uruguay snudde rommet.",
    facts: ["Uruguay vant den avgjørende finalerundekampen 2-1.","Maracanazo er fortsatt Brasils åpne VM-sår.","1950 hadde finalerunde i stedet for vanlig finale."],
    credit: "Unknown author",
    license: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Ademir%20de%20Menezes%2C%20Estadio%2C%201950-08-05%20(377).jpg",
    approved: true,
    mediaType: "photo",
    year: "1950",
    teams: ["Brazil","Uruguay"],
    matchIds: [],
    momentIds: ["maracanazo-1950"],
    tags: ["1950","brazil","uruguay","maracanazo","archive","photo","commons"],
    orientation: "portrait",
    focus: "center",
  },
  {
    id: "alemania-v-hungria-estadio-1954-07-17-583-03-4c568f4f",
    src: "/daily-images/commons/alemania-v-hungria-estadio-1954-07-17-583-03-4c568f4f.jpg",
    title: "1954: Alemania v Hungría, Estadio, 1954-07-17 (583) 03",
    alt: "Arkivbilde fra 1954: Alemania v Hungría, Estadio, 1954-07-17 (583) 03",
    caption: "Arkivbilde fra 1954-sporet i VM-arkivet: Alemania v Hungría, Estadio, 1954-07-17 (583) 03.",
    context: "Bern-finalen er et arkivskap for alle som liker favoritter, regnvær og den typen resultat som gjør at folk endrer tonefall.",
    facts: ["Vest-Tyskland slo Ungarn 3-2.","Kampen er kjent som Mirakelet i Bern.","Ungarn hadde slått Vest-Tyskland 8-3 tidligere i turneringen."],
    credit: "Unknown author",
    license: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Alemania%20v%20Hungr%C3%ADa%2C%20Estadio%2C%201954-07-17%20(583)%2003.jpg",
    approved: true,
    mediaType: "photo",
    year: "1954",
    teams: ["Germany","Hungary"],
    matchIds: [],
    momentIds: ["germany-2014"],
    tags: ["1954","germany","hungary","final","miracle-of-bern","photo","commons"],
    orientation: "landscape",
    focus: "center",
  },
  {
    id: "alfieri-monumental-mundial-78-47d602cf",
    src: "/daily-images/commons/alfieri-monumental-mundial-78-47d602cf.jpg",
    title: "1978: Alfieri monumental mundial 78",
    alt: "Arkivbilde fra 1978: Alfieri monumental mundial 78",
    caption: "Arkivbilde fra 1978-sporet i VM-arkivet: Alfieri monumental mundial 78.",
    context: "Buenos Aires-finalen har alt et privat VM-arkiv liker: konfetti, trykk, ekstraomganger og en vertsnasjon som gjorde kvelden enorm.",
    facts: ["Argentina slo Nederland 3-1 etter ekstraomganger.","Mario Kempes scoret to mål i finalen.","Nederland tapte sin andre strake VM-finale."],
    credit: "Unknown author",
    license: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Alfieri%20monumental%20mundial%2078.jpg",
    approved: true,
    mediaType: "photo",
    year: "1978",
    teams: ["Argentina","Netherlands"],
    matchIds: [],
    momentIds: ["bergkamp-1998"],
    tags: ["1978","argentina","netherlands","final","kempes","photo","commons"],
    orientation: "landscape",
    focus: "center",
  },
  {
    id: "argentina-before-playing-final-9e50448e",
    src: "/daily-images/commons/argentina-before-playing-final-9e50448e.jpg",
    title: "1986: Argentina before playing finale",
    alt: "Arkivbilde fra 1986: Argentina before playing final",
    caption: "Arkivbilde fra 1986-sporet i VM-arkivet: Argentina before playing final.",
    context: "1986-finalen er Maradona-turneringen med sluttstrek: Argentina hadde nerven, Vest-Tyskland hadde opphentingen, og Burruchaga hadde siste løp.",
    facts: ["Argentina slo Vest-Tyskland 3-2.","Burruchaga avgjorde finalen sent.","Maradona var turneringens gravitasjonssenter."],
    credit: "Unknown author",
    license: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Argentina%20before%20playing%20final.jpg",
    approved: true,
    mediaType: "photo",
    year: "1986",
    teams: ["Argentina","Germany"],
    matchIds: [],
    momentIds: ["maradona-1986"],
    tags: ["1986","argentina","germany","maradona","final","photo","commons"],
    orientation: "landscape",
    focus: "center",
  },
  {
    id: "closing-ceremony-stage-at-soccer-city-4782789551-7cc3118d",
    src: "/daily-images/commons/closing-ceremony-stage-at-soccer-city-4782789551-7cc3118d.jpg",
    title: "2010: Closing ceremony stage at Soccer City (4782789551)",
    alt: "Arkivbilde fra 2010: Closing ceremony stage at Soccer City (4782789551)",
    caption: "Arkivbilde fra 2010-sporet i VM-arkivet: Closing ceremony stage at Soccer City (4782789551).",
    context: "2010-finalen er den lave scorens høymesse: Spania trillet, Nederland taklet, og Iniesta skrev punktum da rommet nesten hadde gitt opp.",
    facts: ["Spania slo Nederland 1-0 etter ekstraomganger.","Iniesta scoret finalens eneste mål.","Dette var Spanias første VM-gull."],
    credit: "2010 World Cup - Shine 2010 from Johannesburg, South Africa",
    license: "CC BY 2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Closing%20ceremony%20stage%20at%20Soccer%20City%20(4782789551).jpg",
    approved: true,
    mediaType: "photo",
    year: "2010",
    teams: ["Spain","Netherlands"],
    matchIds: [],
    momentIds: ["spain-2010"],
    tags: ["2010","spain","netherlands","final","iniesta","photo","commons"],
    orientation: "landscape",
    focus: "center",
  },
  {
    id: "2026-fifa-world-cup-federal-interagency-coordination-p-9c3c35ab",
    src: "/daily-images/commons/2026-fifa-world-cup-federal-interagency-coordination-p-9c3c35ab.jpg",
    title: "2026: 2026 VM Federal Interagency Coordination Plan (55118098...",
    alt: "Arkivbilde fra 2026: 2026 FIFA World Cup Federal Interagency Coordination Plan (55118098877)",
    caption: "Arkivbilde fra 2026-sporet i VM-arkivet: 2026 FIFA World Cup Federal Interagency Coordination Plan (55118098877).",
    context: "2026-bildene handler om skala: tre vertsland, 48 lag og en turnering som gjør selv den ryddigste notatblokka litt nervøs.",
    facts: ["2026 blir første VM med 48 lag.","USA, Canada og Mexico deler vertskapet.","Turneringen får 104 kamper."],
    credit: "DHSgov",
    license: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2026%20FIFA%20World%20Cup%20Federal%20Interagency%20Coordination%20Plan%20(55118098877).jpg",
    approved: true,
    mediaType: "photo",
    year: "2026",
    teams: ["USA"],
    matchIds: [],
    momentIds: ["world-cup-2026-format"],
    tags: ["2026","usa","host","venue","format","photo","commons"],
    orientation: "portrait",
    focus: "center",
  },
  {
    id: "fans-uruguayos-celebrando-aa7b5e72",
    src: "/daily-images/commons/fans-uruguayos-celebrando-aa7b5e72.jpg",
    title: "1930: Fans uruguayos celebrando",
    alt: "Arkivbilde fra 1930: Fans uruguayos celebrando",
    caption: "Arkivbilde fra 1930-sporet i VM-arkivet: Fans uruguayos celebrando.",
    context: "Den første VM-finalen gjør arkivet fysisk: korte bukser, lang reise og et mesterskap som ennå ikke visste at det skulle bli en verdenskalender.",
    facts: ["Uruguay slo Argentina 4-2 i finalen.","Finalen ble spilt på Estadio Centenario i Montevideo.","1930-VM hadde bare 13 lag."],
    credit: "Unknown author",
    license: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Fans%20uruguayos%20celebrando.jpg",
    approved: true,
    mediaType: "photo",
    year: "1930",
    teams: ["Uruguay","Argentina"],
    matchIds: [],
    momentIds: ["uruguay-1930"],
    tags: ["1930","final","uruguay","argentina","rimet","early-world-cup","photo","commons"],
    orientation: "landscape",
    focus: "center",
  },
  {
    id: "ademir-de-menezes-691225ee",
    src: "/daily-images/commons/ademir-de-menezes-691225ee.jpg",
    title: "1950: Ademir de Menezes",
    alt: "Arkivbilde fra 1950: Ademir de Menezes",
    caption: "Arkivbilde fra 1950-sporet i VM-arkivet: Ademir de Menezes.",
    context: "1950-bildene bærer VM-historiens mest berømte stillhet: Brasil var vert, favoritt og nesten kronet før Uruguay snudde rommet.",
    facts: ["Uruguay vant den avgjørende finalerundekampen 2-1.","Maracanazo er fortsatt Brasils åpne VM-sår.","1950 hadde finalerunde i stedet for vanlig finale."],
    credit: "Unknown author",
    license: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Ademir%20de%20Menezes.jpg",
    approved: true,
    mediaType: "photo",
    year: "1950",
    teams: ["Brazil","Uruguay"],
    matchIds: [],
    momentIds: ["maracanazo-1950"],
    tags: ["1950","brazil","uruguay","maracanazo","archive","photo","commons"],
    orientation: "portrait",
    focus: "center",
  },
  {
    id: "brazil-v-italia-1970-04-659662f3",
    src: "/daily-images/commons/brazil-v-italia-1970-04-659662f3.jpg",
    title: "1970: Brazil v italia 1970 04",
    alt: "Arkivbilde fra 1970: Brazil v italia 1970 04",
    caption: "Arkivbilde fra 1970-sporet i VM-arkivet: Brazil v italia 1970 04.",
    context: "Mexico 1970 er den vakre standarden alle Brasil-tips later som de har regnet seg frem til, selv når de egentlig bare savner Pelé.",
    facts: ["Brasil slo Italia 4-1 i finalen.","Pelé ble første spiller med tre VM-gull.","Carlos Albertos finalemål er fortsatt taktisk museumsstoff."],
    credit: "Unknown author",
    license: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Brazil%20v%20italia%201970%2004.jpg",
    approved: true,
    mediaType: "photo",
    year: "1970",
    teams: ["Brazil","Italy"],
    matchIds: [],
    momentIds: ["brazil-1970"],
    tags: ["1970","brazil","italy","final","pele","photo","commons"],
    orientation: "landscape",
    focus: "center",
  },
  {
    id: "bundesarchiv-bild-183-n0716-0314-fu-ball-wm-brd-nieder-a9bb7000",
    src: "/daily-images/commons/bundesarchiv-bild-183-n0716-0314-fu-ball-wm-brd-nieder-a9bb7000.jpg",
    title: "1974: Bundesarchiv Bild 183-N0716-0314, Fußball-WM, BRD - Nie...",
    alt: "Arkivbilde fra 1974: Bundesarchiv Bild 183-N0716-0314, Fußball-WM, BRD - Niederlande 2-1",
    caption: "Arkivbilde fra 1974-sporet i VM-arkivet: Bundesarchiv Bild 183-N0716-0314, Fußball-WM, BRD - Niederlande 2-1.",
    context: "1974-finalen er totalfotballens store rettssak: Nederland hadde idéen, Vest-Tyskland hadde pokalen og kjelleren har fortsatt meninger.",
    facts: ["Vest-Tyskland slo Nederland 2-1.","Nederland tok ledelsen før tysk spiller hadde rørt ballen.","Cruyff-generasjonen ble stil uten gull."],
    credit: "Rainer Mittelstädt",
    license: "CC BY-SA 3.0 de",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bundesarchiv%20Bild%20183-N0716-0314%2C%20Fu%C3%9Fball-WM%2C%20BRD%20-%20Niederlande%202-1.jpg",
    approved: true,
    mediaType: "photo",
    year: "1974",
    teams: ["Germany","Netherlands"],
    matchIds: [],
    momentIds: ["netherlands-brazil-1998"],
    tags: ["1974","germany","netherlands","cruyff","total-football","final","photo","commons"],
    orientation: "landscape",
    focus: "center",
  },
  {
    id: "ardiles-v-holanda-7f70e7f3",
    src: "/daily-images/commons/ardiles-v-holanda-7f70e7f3.jpg",
    title: "1978: Ardiles v holanda",
    alt: "Arkivbilde fra 1978: Ardiles v holanda",
    caption: "Arkivbilde fra 1978-sporet i VM-arkivet: Ardiles v holanda.",
    context: "Buenos Aires-finalen har alt et privat VM-arkiv liker: konfetti, trykk, ekstraomganger og en vertsnasjon som gjorde kvelden enorm.",
    facts: ["Argentina slo Nederland 3-1 etter ekstraomganger.","Mario Kempes scoret to mål i finalen.","Nederland tapte sin andre strake VM-finale."],
    credit: "Unknown author",
    license: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Ardiles%20v%20holanda.jpg",
    approved: true,
    mediaType: "photo",
    year: "1978",
    teams: ["Argentina","Netherlands"],
    matchIds: [],
    momentIds: ["bergkamp-1998"],
    tags: ["1978","argentina","netherlands","final","kempes","photo","commons"],
    orientation: "landscape",
    focus: "center",
  },
  {
    id: "fabio-grosso-in-world-cup-final-2006-d1e0982c",
    src: "/daily-images/commons/fabio-grosso-in-world-cup-final-2006-d1e0982c.png",
    title: "2006: Fabio Grosso in VM finale 2006",
    alt: "Arkivbilde fra 2006: Fabio Grosso in world cup final 2006",
    caption: "Arkivbilde fra 2006-sporet i VM-arkivet: Fabio Grosso in world cup final 2006.",
    context: "Berlin 2006 er finalen som minner alle om at VM-historie ofte skrives etter 120 minutter og med litt for mye puls.",
    facts: ["Italia slo Frankrike på straffer.","Kampen endte 1-1 etter ekstraomganger.","Zidane spilte sin siste landskamp."],
    credit: "David Ruddell",
    license: "CC BY 2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Fabio%20Grosso%20in%20world%20cup%20final%202006.png",
    approved: true,
    mediaType: "photo",
    year: "2006",
    teams: ["Italy","France"],
    matchIds: [],
    momentIds: ["baggio-1994","france-1998"],
    tags: ["2006","italy","france","final","penalties","zidane","photo","commons"],
    orientation: "portrait",
    focus: "center",
  },
  {
    id: "dutch-fan-at-final-world-cup-game-4783378268-ba329189",
    src: "/daily-images/commons/dutch-fan-at-final-world-cup-game-4783378268-ba329189.jpg",
    title: "2010: Dutch fan at finale VM game (4783378268)",
    alt: "Arkivbilde fra 2010: Dutch fan at final World Cup game (4783378268)",
    caption: "Arkivbilde fra 2010-sporet i VM-arkivet: Dutch fan at final World Cup game (4783378268).",
    context: "2010-finalen er den lave scorens høymesse: Spania trillet, Nederland taklet, og Iniesta skrev punktum da rommet nesten hadde gitt opp.",
    facts: ["Spania slo Nederland 1-0 etter ekstraomganger.","Iniesta scoret finalens eneste mål.","Dette var Spanias første VM-gull."],
    credit: "2010 World Cup - Shine 2010 from Johannesburg, South Africa",
    license: "CC BY 2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Dutch%20fan%20at%20final%20World%20Cup%20game%20(4783378268).jpg",
    approved: true,
    mediaType: "photo",
    year: "2010",
    teams: ["Spain","Netherlands"],
    matchIds: [],
    momentIds: ["spain-2010"],
    tags: ["2010","spain","netherlands","final","iniesta","photo","commons"],
    orientation: "landscape",
    focus: "center",
  },
  {
    id: "alemania-v-hungria-estadio-1954-07-17-583-05-b1613085",
    src: "/daily-images/commons/alemania-v-hungria-estadio-1954-07-17-583-05-b1613085.jpg",
    title: "1954: Alemania v Hungría, Estadio, 1954-07-17 (583) 05",
    alt: "Arkivbilde fra 1954: Alemania v Hungría, Estadio, 1954-07-17 (583) 05",
    caption: "Arkivbilde fra 1954-sporet i VM-arkivet: Alemania v Hungría, Estadio, 1954-07-17 (583) 05.",
    context: "Bern-finalen er et arkivskap for alle som liker favoritter, regnvær og den typen resultat som gjør at folk endrer tonefall.",
    facts: ["Vest-Tyskland slo Ungarn 3-2.","Kampen er kjent som Mirakelet i Bern.","Ungarn hadde slått Vest-Tyskland 8-3 tidligere i turneringen."],
    credit: "Unknown author",
    license: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Alemania%20v%20Hungr%C3%ADa%2C%20Estadio%2C%201954-07-17%20(583)%2005.jpg",
    approved: true,
    mediaType: "photo",
    year: "1954",
    teams: ["Germany","Hungary"],
    matchIds: [],
    momentIds: ["germany-2014"],
    tags: ["1954","germany","hungary","final","miracle-of-bern","photo","commons"],
    orientation: "landscape",
    focus: "center",
  },
  {
    id: "brazil-v-italia-1970-05-1260ae07",
    src: "/daily-images/commons/brazil-v-italia-1970-05-1260ae07.jpg",
    title: "1970: Brazil v italia 1970 05",
    alt: "Arkivbilde fra 1970: Brazil v italia 1970 05",
    caption: "Arkivbilde fra 1970-sporet i VM-arkivet: Brazil v italia 1970 05.",
    context: "Mexico 1970 er den vakre standarden alle Brasil-tips later som de har regnet seg frem til, selv når de egentlig bare savner Pelé.",
    facts: ["Brasil slo Italia 4-1 i finalen.","Pelé ble første spiller med tre VM-gull.","Carlos Albertos finalemål er fortsatt taktisk museumsstoff."],
    credit: "Unknown author",
    license: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Brazil%20v%20italia%201970%2005.jpg",
    approved: true,
    mediaType: "photo",
    year: "1970",
    teams: ["Brazil","Italy"],
    matchIds: [],
    momentIds: ["brazil-1970"],
    tags: ["1970","brazil","italy","final","pele","photo","commons"],
    orientation: "landscape",
    focus: "center",
  },
  {
    id: "bundesarchiv-bild-183-n0716-0314-fu-ball-wm-brd-nieder-dfa57b4f",
    src: "/daily-images/commons/bundesarchiv-bild-183-n0716-0314-fu-ball-wm-brd-nieder-dfa57b4f.jpg",
    title: "1974: Bundesarchiv Bild 183-N0716-0314, Fußball-WM, BRD - Nie...",
    alt: "Arkivbilde fra 1974: Bundesarchiv Bild 183-N0716-0314, Fußball-WM, BRD - Niederlande 2-1a-2",
    caption: "Arkivbilde fra 1974-sporet i VM-arkivet: Bundesarchiv Bild 183-N0716-0314, Fußball-WM, BRD - Niederlande 2-1a-2.",
    context: "1974-finalen er totalfotballens store rettssak: Nederland hadde idéen, Vest-Tyskland hadde pokalen og kjelleren har fortsatt meninger.",
    facts: ["Vest-Tyskland slo Nederland 2-1.","Nederland tok ledelsen før tysk spiller hadde rørt ballen.","Cruyff-generasjonen ble stil uten gull."],
    credit: "Bundesarchiv_Bild_183-N0716-0314,_Fußball-WM,_BRD_-_Niederlande_2-1a.jpg : * Bundesarchiv_Bild_183-N0716-0314,_Fußball-WM,_BRD_-_Niederlande_2-1.jpg : Mittelstädt, Rainer derivative work: Linksfuss ( talk ) derivative work: MachoCarioca ( talk )",
    license: "CC BY-SA 3.0 de",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bundesarchiv%20Bild%20183-N0716-0314%2C%20Fu%C3%9Fball-WM%2C%20BRD%20-%20Niederlande%202-1a-2.jpg",
    approved: true,
    mediaType: "photo",
    year: "1974",
    teams: ["Germany","Netherlands"],
    matchIds: [],
    momentIds: ["netherlands-brazil-1998"],
    tags: ["1974","germany","netherlands","cruyff","total-football","final","photo","commons"],
    orientation: "portrait",
    focus: "center",
  },
  {
    id: "argentina-celebrando-copa-cropped-db880f49",
    src: "/daily-images/commons/argentina-celebrando-copa-cropped-db880f49.jpg",
    title: "1986: Argentina celebrando copa (cropped)",
    alt: "Arkivbilde fra 1986: Argentina celebrando copa (cropped)",
    caption: "Arkivbilde fra 1986-sporet i VM-arkivet: Argentina celebrando copa (cropped).",
    context: "1986-finalen er Maradona-turneringen med sluttstrek: Argentina hadde nerven, Vest-Tyskland hadde opphentingen, og Burruchaga hadde siste løp.",
    facts: ["Argentina slo Vest-Tyskland 3-2.","Burruchaga avgjorde finalen sent.","Maradona var turneringens gravitasjonssenter."],
    credit: "Unknown author",
    license: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Argentina%20celebrando%20copa%20(cropped).jpg",
    approved: true,
    mediaType: "photo",
    year: "1986",
    teams: ["Argentina","Germany"],
    matchIds: [],
    momentIds: ["maradona-1986"],
    tags: ["1986","argentina","germany","maradona","final","photo","commons"],
    orientation: "portrait",
    focus: "top",
  },
  {
    id: "football-stadium-berlin-d9415e4f",
    src: "/daily-images/commons/football-stadium-berlin-d9415e4f.jpg",
    title: "2006: Football-stadium-berlin",
    alt: "Arkivbilde fra 2006: Football-stadium-berlin",
    caption: "Arkivbilde fra 2006-sporet i VM-arkivet: Football-stadium-berlin.",
    context: "Berlin 2006 er finalen som minner alle om at VM-historie ofte skrives etter 120 minutter og med litt for mye puls.",
    facts: ["Italia slo Frankrike på straffer.","Kampen endte 1-1 etter ekstraomganger.","Zidane spilte sin siste landskamp."],
    credit: "Pixel-Sepp",
    license: "CC0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Football-stadium-berlin.jpg",
    approved: true,
    mediaType: "photo",
    year: "2006",
    teams: ["Italy","France"],
    matchIds: [],
    momentIds: ["baggio-1994","france-1998"],
    tags: ["2006","italy","france","final","penalties","zidane","photo","commons"],
    orientation: "landscape",
    focus: "center",
  },
  {
    id: "dutch-fans-with-slaughtered-octopus-on-their-heads-a-w-61d8d56b",
    src: "/daily-images/commons/dutch-fans-with-slaughtered-octopus-on-their-heads-a-w-61d8d56b.jpg",
    title: "2010: Dutch fans with slaughtered octopus on their heads, a w...",
    alt: "Arkivbilde fra 2010: Dutch fans with slaughtered octopus on their heads, a warning to Paul if Netherlands lose tonight (4783377078)",
    caption: "Arkivbilde fra 2010-sporet i VM-arkivet: Dutch fans with slaughtered octopus on their heads, a warning to Paul if Netherlands lose tonight (4783377078).",
    context: "2010-finalen er den lave scorens høymesse: Spania trillet, Nederland taklet, og Iniesta skrev punktum da rommet nesten hadde gitt opp.",
    facts: ["Spania slo Nederland 1-0 etter ekstraomganger.","Iniesta scoret finalens eneste mål.","Dette var Spanias første VM-gull."],
    credit: "2010 World Cup - Shine 2010 from Johannesburg, South Africa",
    license: "CC BY 2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Dutch%20fans%20with%20slaughtered%20octopus%20on%20their%20heads%2C%20a%20warning%20to%20Paul%20if%20Netherlands%20lose%20tonight%20(4783377078).jpg",
    approved: true,
    mediaType: "photo",
    year: "2010",
    teams: ["Spain","Netherlands"],
    matchIds: [],
    momentIds: ["spain-2010"],
    tags: ["2010","spain","netherlands","final","iniesta","photo","commons"],
    orientation: "landscape",
    focus: "center",
  },
  {
    id: "nasazzi-ferreira-final-a8eac938",
    src: "/daily-images/commons/nasazzi-ferreira-final-a8eac938.jpg",
    title: "1930: Nasazzi ferreira finale",
    alt: "Arkivbilde fra 1930: Nasazzi ferreira final",
    caption: "Arkivbilde fra 1930-sporet i VM-arkivet: Nasazzi ferreira final.",
    context: "Den første VM-finalen gjør arkivet fysisk: korte bukser, lang reise og et mesterskap som ennå ikke visste at det skulle bli en verdenskalender.",
    facts: ["Uruguay slo Argentina 4-2 i finalen.","Finalen ble spilt på Estadio Centenario i Montevideo.","1930-VM hadde bare 13 lag."],
    credit: "Unknown author",
    license: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Nasazzi%20ferreira%20final.jpg",
    approved: true,
    mediaType: "photo",
    year: "1930",
    teams: ["Uruguay","Argentina"],
    matchIds: [],
    momentIds: ["uruguay-1930"],
    tags: ["1930","final","uruguay","argentina","rimet","early-world-cup","photo","commons"],
    orientation: "landscape",
    focus: "center",
  },
  {
    id: "augusto-augusto-da-costa-capitaine-du-bresil-en-finale-801d56bd",
    src: "/daily-images/commons/augusto-augusto-da-costa-capitaine-du-bresil-en-finale-801d56bd.jpg",
    title: "1950: Augusto 'Augusto' da Costa, capitaine du Brésil en fina...",
    alt: "Arkivbilde fra 1950: Augusto 'Augusto' da Costa, capitaine du Brésil en finale de Coupe du monde de football 1950 (cropped)",
    caption: "Arkivbilde fra 1950-sporet i VM-arkivet: Augusto 'Augusto' da Costa, capitaine du Brésil en finale de Coupe du monde de football 1950 (cropped).",
    context: "1950-bildene bærer VM-historiens mest berømte stillhet: Brasil var vert, favoritt og nesten kronet før Uruguay snudde rommet.",
    facts: ["Uruguay vant den avgjørende finalerundekampen 2-1.","Maracanazo er fortsatt Brasils åpne VM-sår.","1950 hadde finalerunde i stedet for vanlig finale."],
    credit: "Fundo Correio da Manhã.",
    license: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Augusto%20'Augusto'%20da%20Costa%2C%20capitaine%20du%20Br%C3%A9sil%20en%20finale%20de%20Coupe%20du%20monde%20de%20football%201950%20(cropped).jpg",
    approved: true,
    mediaType: "photo",
    year: "1950",
    teams: ["Brazil","Uruguay"],
    matchIds: [],
    momentIds: ["maracanazo-1950"],
    tags: ["1950","brazil","uruguay","maracanazo","archive","photo","commons"],
    orientation: "portrait",
    focus: "top",
  },
  {
    id: "brazil-v-italy-1970-06-8b62512f",
    src: "/daily-images/commons/brazil-v-italy-1970-06-8b62512f.jpg",
    title: "1970: Brazil v italy 1970 06",
    alt: "Arkivbilde fra 1970: Brazil v italy 1970 06",
    caption: "Arkivbilde fra 1970-sporet i VM-arkivet: Brazil v italy 1970 06.",
    context: "Mexico 1970 er den vakre standarden alle Brasil-tips later som de har regnet seg frem til, selv når de egentlig bare savner Pelé.",
    facts: ["Brasil slo Italia 4-1 i finalen.","Pelé ble første spiller med tre VM-gull.","Carlos Albertos finalemål er fortsatt taktisk museumsstoff."],
    credit: "Unknown author",
    license: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Brazil%20v%20italy%201970%2006.jpg",
    approved: true,
    mediaType: "photo",
    year: "1970",
    teams: ["Brazil","Italy"],
    matchIds: [],
    momentIds: ["brazil-1970"],
    tags: ["1970","brazil","italy","final","pele","photo","commons"],
    orientation: "portrait",
    focus: "center",
  },
  {
    id: "bundesarchiv-bild-183-n0716-0314-fu-ball-wm-brd-nieder-973d86b6",
    src: "/daily-images/commons/bundesarchiv-bild-183-n0716-0314-fu-ball-wm-brd-nieder-973d86b6.jpg",
    title: "1974: Bundesarchiv Bild 183-N0716-0314, Fußball-WM, BRD - Nie...",
    alt: "Arkivbilde fra 1974: Bundesarchiv Bild 183-N0716-0314, Fußball-WM, BRD - Niederlande 2-1a",
    caption: "Arkivbilde fra 1974-sporet i VM-arkivet: Bundesarchiv Bild 183-N0716-0314, Fußball-WM, BRD - Niederlande 2-1a.",
    context: "1974-finalen er totalfotballens store rettssak: Nederland hadde idéen, Vest-Tyskland hadde pokalen og kjelleren har fortsatt meninger.",
    facts: ["Vest-Tyskland slo Nederland 2-1.","Nederland tok ledelsen før tysk spiller hadde rørt ballen.","Cruyff-generasjonen ble stil uten gull."],
    credit: "Bundesarchiv_Bild_183-N0716-0314,_Fußball-WM,_BRD_-_Niederlande_2-1.jpg : Mittelstädt, Rainer derivative work: Linksfuss ( talk )",
    license: "CC BY-SA 3.0 de",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bundesarchiv%20Bild%20183-N0716-0314%2C%20Fu%C3%9Fball-WM%2C%20BRD%20-%20Niederlande%202-1a.jpg",
    approved: true,
    mediaType: "photo",
    year: "1974",
    teams: ["Germany","Netherlands"],
    matchIds: [],
    momentIds: ["netherlands-brazil-1998"],
    tags: ["1974","germany","netherlands","cruyff","total-football","final","photo","commons"],
    orientation: "portrait",
    focus: "center",
  },
  {
    id: "arg-ned-1978-8e212984",
    src: "/daily-images/commons/arg-ned-1978-8e212984.png",
    title: "1978: ARG-NED 1978",
    alt: "Diagram fra 1978: ARG-NED 1978",
    caption: "Diagram/oppstilling fra 1978-arkivet: ARG-NED 1978.",
    context: "Buenos Aires-finalen har alt et privat VM-arkiv liker: konfetti, trykk, ekstraomganger og en vertsnasjon som gjorde kvelden enorm.",
    facts: ["Argentina slo Nederland 3-1 etter ekstraomganger.","Mario Kempes scoret to mål i finalen.","Nederland tapte sin andre strake VM-finale."],
    credit: "Oldsteve666",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:ARG-NED%201978.svg",
    approved: true,
    mediaType: "diagram",
    year: "1978",
    teams: ["Argentina","Netherlands"],
    matchIds: [],
    momentIds: ["bergkamp-1998"],
    tags: ["1978","argentina","netherlands","final","kempes","diagram","commons"],
    orientation: "portrait",
    focus: "center",
  },
  {
    id: "fan-outside-soccer-city-for-final-game-4783375624-e35eecb9",
    src: "/daily-images/commons/fan-outside-soccer-city-for-final-game-4783375624-e35eecb9.jpg",
    title: "2010: Fan outside Soccer City for finale game (4783375624)",
    alt: "Arkivbilde fra 2010: Fan outside Soccer City for final game (4783375624)",
    caption: "Arkivbilde fra 2010-sporet i VM-arkivet: Fan outside Soccer City for final game (4783375624).",
    context: "2010-finalen er den lave scorens høymesse: Spania trillet, Nederland taklet, og Iniesta skrev punktum da rommet nesten hadde gitt opp.",
    facts: ["Spania slo Nederland 1-0 etter ekstraomganger.","Iniesta scoret finalens eneste mål.","Dette var Spanias første VM-gull."],
    credit: "2010 World Cup - Shine 2010 from Johannesburg, South Africa",
    license: "CC BY 2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Fan%20outside%20Soccer%20City%20for%20final%20game%20(4783375624).jpg",
    approved: true,
    mediaType: "photo",
    year: "2010",
    teams: ["Spain","Netherlands"],
    matchIds: [],
    momentIds: ["spain-2010"],
    tags: ["2010","spain","netherlands","final","iniesta","photo","commons"],
    orientation: "landscape",
    focus: "center",
  },
  {
    id: "2026-fifa-world-cup-federal-interagency-coordination-p-05301e47",
    src: "/daily-images/commons/2026-fifa-world-cup-federal-interagency-coordination-p-05301e47.jpg",
    title: "2026: 2026 VM Federal Interagency Coordination Plan (55119176...",
    alt: "Arkivbilde fra 2026: 2026 FIFA World Cup Federal Interagency Coordination Plan (55119176263)",
    caption: "Arkivbilde fra 2026-sporet i VM-arkivet: 2026 FIFA World Cup Federal Interagency Coordination Plan (55119176263).",
    context: "2026-bildene handler om skala: tre vertsland, 48 lag og en turnering som gjør selv den ryddigste notatblokka litt nervøs.",
    facts: ["2026 blir første VM med 48 lag.","USA, Canada og Mexico deler vertskapet.","Turneringen får 104 kamper."],
    credit: "DHSgov",
    license: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2026%20FIFA%20World%20Cup%20Federal%20Interagency%20Coordination%20Plan%20(55119176263).jpg",
    approved: true,
    mediaType: "photo",
    year: "2026",
    teams: ["USA"],
    matchIds: [],
    momentIds: ["world-cup-2026-format"],
    tags: ["2026","usa","host","venue","format","photo","commons"],
    orientation: "landscape",
    focus: "center",
  },
  {
    id: "nasazzi-ferreira-dce53dcd",
    src: "/daily-images/commons/nasazzi-ferreira-dce53dcd.jpg",
    title: "1930: Nasazzi ferreira",
    alt: "Arkivbilde fra 1930: Nasazzi ferreira",
    caption: "Arkivbilde fra 1930-sporet i VM-arkivet: Nasazzi ferreira.",
    context: "Den første VM-finalen gjør arkivet fysisk: korte bukser, lang reise og et mesterskap som ennå ikke visste at det skulle bli en verdenskalender.",
    facts: ["Uruguay slo Argentina 4-2 i finalen.","Finalen ble spilt på Estadio Centenario i Montevideo.","1930-VM hadde bare 13 lag."],
    credit: "Unknown author",
    license: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Nasazzi%20ferreira.jpg",
    approved: true,
    mediaType: "photo",
    year: "1930",
    teams: ["Uruguay","Argentina"],
    matchIds: [],
    momentIds: ["uruguay-1930"],
    tags: ["1930","final","uruguay","argentina","rimet","early-world-cup","photo","commons"],
    orientation: "portrait",
    focus: "center",
  },
  {
    id: "pele-celebrating-1970-cropped-547c4f37",
    src: "/daily-images/commons/pele-celebrating-1970-cropped-547c4f37.jpg",
    title: "1970: Pele celebrating 1970 (cropped)",
    alt: "Arkivbilde fra 1970: Pele celebrating 1970 (cropped)",
    caption: "Arkivbilde fra 1970-sporet i VM-arkivet: Pele celebrating 1970 (cropped).",
    context: "Mexico 1970 er den vakre standarden alle Brasil-tips later som de har regnet seg frem til, selv når de egentlig bare savner Pelé.",
    facts: ["Brasil slo Italia 4-1 i finalen.","Pelé ble første spiller med tre VM-gull.","Carlos Albertos finalemål er fortsatt taktisk museumsstoff."],
    credit: "Unknown - Distributed by the Associated Press",
    license: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Pele%20celebrating%201970%20(cropped).jpg",
    approved: true,
    mediaType: "photo",
    year: "1970",
    teams: ["Brazil","Italy"],
    matchIds: [],
    momentIds: ["brazil-1970"],
    tags: ["1970","brazil","italy","final","pele","photo","commons"],
    orientation: "landscape",
    focus: "top",
  },
  {
    id: "argentina-germany-entering-f29e6cc4",
    src: "/daily-images/commons/argentina-germany-entering-f29e6cc4.jpg",
    title: "1986: Argentina germany entering",
    alt: "Arkivbilde fra 1986: Argentina germany entering",
    caption: "Arkivbilde fra 1986-sporet i VM-arkivet: Argentina germany entering.",
    context: "1986-finalen er Maradona-turneringen med sluttstrek: Argentina hadde nerven, Vest-Tyskland hadde opphentingen, og Burruchaga hadde siste løp.",
    facts: ["Argentina slo Vest-Tyskland 3-2.","Burruchaga avgjorde finalen sent.","Maradona var turneringens gravitasjonssenter."],
    credit: "Unknown author",
    license: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Argentina%20germany%20entering.jpg",
    approved: true,
    mediaType: "photo",
    year: "1986",
    teams: ["Argentina","Germany"],
    matchIds: [],
    momentIds: ["maradona-1986"],
    tags: ["1986","argentina","germany","maradona","final","photo","commons"],
    orientation: "landscape",
    focus: "center",
  },
  {
    id: "fifa-world-cup-2010-final-anthems-79a6989d",
    src: "/daily-images/commons/fifa-world-cup-2010-final-anthems-79a6989d.jpg",
    title: "2010: VM 2010 finale anthems",
    alt: "Arkivbilde fra 2010: FIFA World Cup 2010 Final anthems",
    caption: "Arkivbilde fra 2010-sporet i VM-arkivet: FIFA World Cup 2010 Final anthems.",
    context: "2010-finalen er den lave scorens høymesse: Spania trillet, Nederland taklet, og Iniesta skrev punktum da rommet nesten hadde gitt opp.",
    facts: ["Spania slo Nederland 1-0 etter ekstraomganger.","Iniesta scoret finalens eneste mål.","Dette var Spanias første VM-gull."],
    credit: "Christophe Badoux",
    license: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:FIFA%20World%20Cup%202010%20Final%20anthems.jpg",
    approved: true,
    mediaType: "photo",
    year: "2010",
    teams: ["Spain","Netherlands"],
    matchIds: [],
    momentIds: ["spain-2010"],
    tags: ["2010","spain","netherlands","final","iniesta","photo","commons"],
    orientation: "landscape",
    focus: "center",
  },
  {
    id: "2026-fifa-world-cup-federal-interagency-coordination-p-e0df24c6",
    src: "/daily-images/commons/2026-fifa-world-cup-federal-interagency-coordination-p-e0df24c6.jpg",
    title: "2026: 2026 VM Federal Interagency Coordination Plan (55119176...",
    alt: "Arkivbilde fra 2026: 2026 FIFA World Cup Federal Interagency Coordination Plan (55119176333)",
    caption: "Arkivbilde fra 2026-sporet i VM-arkivet: 2026 FIFA World Cup Federal Interagency Coordination Plan (55119176333).",
    context: "2026-bildene handler om skala: tre vertsland, 48 lag og en turnering som gjør selv den ryddigste notatblokka litt nervøs.",
    facts: ["2026 blir første VM med 48 lag.","USA, Canada og Mexico deler vertskapet.","Turneringen får 104 kamper."],
    credit: "DHSgov",
    license: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2026%20FIFA%20World%20Cup%20Federal%20Interagency%20Coordination%20Plan%20(55119176333).jpg",
    approved: true,
    mediaType: "photo",
    year: "2026",
    teams: ["USA"],
    matchIds: [],
    momentIds: ["world-cup-2026-format"],
    tags: ["2026","usa","host","venue","format","photo","commons"],
    orientation: "landscape",
    focus: "center",
  },
  {
    id: "pablo-dorado-cropped-caa7c4bb",
    src: "/daily-images/commons/pablo-dorado-cropped-caa7c4bb.jpg",
    title: "1930: Pablo Dorado (cropped)",
    alt: "Arkivbilde fra 1930: Pablo Dorado (cropped)",
    caption: "Arkivbilde fra 1930-sporet i VM-arkivet: Pablo Dorado (cropped).",
    context: "Den første VM-finalen gjør arkivet fysisk: korte bukser, lang reise og et mesterskap som ennå ikke visste at det skulle bli en verdenskalender.",
    facts: ["Uruguay slo Argentina 4-2 i finalen.","Finalen ble spilt på Estadio Centenario i Montevideo.","1930-VM hadde bare 13 lag."],
    credit: "Unknown author",
    license: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Pablo%20Dorado%20(cropped).JPG",
    approved: true,
    mediaType: "photo",
    year: "1930",
    teams: ["Uruguay","Argentina"],
    matchIds: [],
    momentIds: ["uruguay-1930"],
    tags: ["1930","final","uruguay","argentina","rimet","early-world-cup","photo","commons"],
    orientation: "portrait",
    focus: "top",
  },
  {
    id: "pedrocea-8e1951be",
    src: "/daily-images/commons/pedrocea-8e1951be.jpg",
    title: "1930: PedroCea",
    alt: "Arkivbilde fra 1930: PedroCea",
    caption: "Arkivbilde fra 1930-sporet i VM-arkivet: PedroCea.",
    context: "Den første VM-finalen gjør arkivet fysisk: korte bukser, lang reise og et mesterskap som ennå ikke visste at det skulle bli en verdenskalender.",
    facts: ["Uruguay slo Argentina 4-2 i finalen.","Finalen ble spilt på Estadio Centenario i Montevideo.","1930-VM hadde bare 13 lag."],
    credit: "Uruguay1930.JPG : Desconocido derivative work: Gonchibolso12 ( talk )",
    license: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:PedroCea.JPG",
    approved: true,
    mediaType: "photo",
    year: "1930",
    teams: ["Uruguay","Argentina"],
    matchIds: [],
    momentIds: ["uruguay-1930"],
    tags: ["1930","final","uruguay","argentina","rimet","early-world-cup","photo","commons"],
    orientation: "portrait",
    focus: "center",
  },
  {
    id: "peucelle-gol-vs-uruguay-31789443",
    src: "/daily-images/commons/peucelle-gol-vs-uruguay-31789443.jpg",
    title: "1930: Peucelle gol vs uruguay",
    alt: "Arkivbilde fra 1930: Peucelle gol vs uruguay",
    caption: "Arkivbilde fra 1930-sporet i VM-arkivet: Peucelle gol vs uruguay.",
    context: "Den første VM-finalen gjør arkivet fysisk: korte bukser, lang reise og et mesterskap som ennå ikke visste at det skulle bli en verdenskalender.",
    facts: ["Uruguay slo Argentina 4-2 i finalen.","Finalen ble spilt på Estadio Centenario i Montevideo.","1930-VM hadde bare 13 lag."],
    credit: "Unknown author",
    license: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Peucelle%20gol%20vs%20uruguay.jpg",
    approved: true,
    mediaType: "photo",
    year: "1930",
    teams: ["Uruguay","Argentina"],
    matchIds: [],
    momentIds: ["uruguay-1930"],
    tags: ["1930","final","uruguay","argentina","rimet","early-world-cup","photo","commons"],
    orientation: "landscape",
    focus: "center",
  },
  {
    id: "santos-iriarte-cropped-c41e0c7f",
    src: "/daily-images/commons/santos-iriarte-cropped-c41e0c7f.jpg",
    title: "1930: Santos Iriarte (cropped)",
    alt: "Arkivbilde fra 1930: Santos Iriarte (cropped)",
    caption: "Arkivbilde fra 1930-sporet i VM-arkivet: Santos Iriarte (cropped).",
    context: "Den første VM-finalen gjør arkivet fysisk: korte bukser, lang reise og et mesterskap som ennå ikke visste at det skulle bli en verdenskalender.",
    facts: ["Uruguay slo Argentina 4-2 i finalen.","Finalen ble spilt på Estadio Centenario i Montevideo.","1930-VM hadde bare 13 lag."],
    credit: "Unknown author",
    license: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Santos%20Iriarte%20(cropped).JPG",
    approved: true,
    mediaType: "photo",
    year: "1930",
    teams: ["Uruguay","Argentina"],
    matchIds: [],
    momentIds: ["uruguay-1930"],
    tags: ["1930","final","uruguay","argentina","rimet","early-world-cup","photo","commons"],
    orientation: "portrait",
    focus: "top",
  },
  {
    id: "stabile-goal-v-uruguay-1930-3ac996e4",
    src: "/daily-images/commons/stabile-goal-v-uruguay-1930-3ac996e4.jpg",
    title: "1930: Stabile goal v uruguay 1930",
    alt: "Arkivbilde fra 1930: Stabile goal v uruguay 1930",
    caption: "Arkivbilde fra 1930-sporet i VM-arkivet: Stabile goal v uruguay 1930.",
    context: "Den første VM-finalen gjør arkivet fysisk: korte bukser, lang reise og et mesterskap som ennå ikke visste at det skulle bli en verdenskalender.",
    facts: ["Uruguay slo Argentina 4-2 i finalen.","Finalen ble spilt på Estadio Centenario i Montevideo.","1930-VM hadde bare 13 lag."],
    credit: "Unknown author",
    license: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Stabile%20goal%20v%20uruguay%201930.jpg",
    approved: true,
    mediaType: "photo",
    year: "1930",
    teams: ["Uruguay","Argentina"],
    matchIds: [],
    momentIds: ["uruguay-1930"],
    tags: ["1930","final","uruguay","argentina","rimet","early-world-cup","photo","commons"],
    orientation: "landscape",
    focus: "center",
  },
  {
    id: "uru-arg-1930-07-30-461e6b6e",
    src: "/daily-images/commons/uru-arg-1930-07-30-461e6b6e.png",
    title: "1930: URU-ARG 1930-07-30",
    alt: "Diagram fra 1930: URU-ARG 1930-07-30",
    caption: "Diagram/oppstilling fra 1930-arkivet: URU-ARG 1930-07-30.",
    context: "Den første VM-finalen gjør arkivet fysisk: korte bukser, lang reise og et mesterskap som ennå ikke visste at det skulle bli en verdenskalender.",
    facts: ["Uruguay slo Argentina 4-2 i finalen.","Finalen ble spilt på Estadio Centenario i Montevideo.","1930-VM hadde bare 13 lag."],
    credit: "S.A. Julio",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:URU-ARG%201930-07-30.svg",
    approved: true,
    mediaType: "diagram",
    year: "1930",
    teams: ["Uruguay","Argentina"],
    matchIds: [],
    momentIds: ["uruguay-1930"],
    tags: ["1930","final","uruguay","argentina","rimet","early-world-cup","diagram","commons"],
    orientation: "portrait",
    focus: "center",
  },
  {
    id: "uru-arg-1930-fin-cm-he-604f8f8d",
    src: "/daily-images/commons/uru-arg-1930-fin-cm-he-604f8f8d.png",
    title: "1930: URU-ARG 1930-FIN-CM (he)",
    alt: "Diagram fra 1930: URU-ARG 1930-FIN-CM (he)",
    caption: "Diagram/oppstilling fra 1930-arkivet: URU-ARG 1930-FIN-CM (he).",
    context: "Den første VM-finalen gjør arkivet fysisk: korte bukser, lang reise og et mesterskap som ennå ikke visste at det skulle bli en verdenskalender.",
    facts: ["Uruguay slo Argentina 4-2 i finalen.","Finalen ble spilt på Estadio Centenario i Montevideo.","1930-VM hadde bare 13 lag."],
    credit: "Queix",
    license: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:URU-ARG%201930-FIN-CM%20(he).svg",
    approved: true,
    mediaType: "diagram",
    year: "1930",
    teams: ["Uruguay","Argentina"],
    matchIds: [],
    momentIds: ["uruguay-1930"],
    tags: ["1930","final","uruguay","argentina","rimet","early-world-cup","diagram","commons"],
    orientation: "portrait",
    focus: "center",
  },
  {
    id: "uru-arg-1930-fin-cm-072f4915",
    src: "/daily-images/commons/uru-arg-1930-fin-cm-072f4915.png",
    title: "1930: URU-ARG 1930-FIN-CM",
    alt: "Diagram fra 1930: URU-ARG 1930-FIN-CM",
    caption: "Diagram/oppstilling fra 1930-arkivet: URU-ARG 1930-FIN-CM.",
    context: "Den første VM-finalen gjør arkivet fysisk: korte bukser, lang reise og et mesterskap som ennå ikke visste at det skulle bli en verdenskalender.",
    facts: ["Uruguay slo Argentina 4-2 i finalen.","Finalen ble spilt på Estadio Centenario i Montevideo.","1930-VM hadde bare 13 lag."],
    credit: "Queix",
    license: "CC BY-SA 3.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:URU-ARG%201930-FIN-CM.svg",
    approved: true,
    mediaType: "diagram",
    year: "1930",
    teams: ["Uruguay","Argentina"],
    matchIds: [],
    momentIds: ["uruguay-1930"],
    tags: ["1930","final","uruguay","argentina","rimet","early-world-cup","diagram","commons"],
    orientation: "portrait",
    focus: "center",
  },
  {
    id: "uruguay-1930-festejando-su-victoria-68e8880b",
    src: "/daily-images/commons/uruguay-1930-festejando-su-victoria-68e8880b.jpg",
    title: "1930: Uruguay 1930 festejando su victoria",
    alt: "Arkivbilde fra 1930: Uruguay 1930 festejando su victoria",
    caption: "Arkivbilde fra 1930-sporet i VM-arkivet: Uruguay 1930 festejando su victoria.",
    context: "Den første VM-finalen gjør arkivet fysisk: korte bukser, lang reise og et mesterskap som ennå ikke visste at det skulle bli en verdenskalender.",
    facts: ["Uruguay slo Argentina 4-2 i finalen.","Finalen ble spilt på Estadio Centenario i Montevideo.","1930-VM hadde bare 13 lag."],
    credit: "Th35nak35aja",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Uruguay%201930%20festejando%20su%20victoria.jpg",
    approved: true,
    mediaType: "photo",
    year: "1930",
    teams: ["Uruguay","Argentina"],
    matchIds: [],
    momentIds: ["uruguay-1930"],
    tags: ["1930","final","uruguay","argentina","rimet","early-world-cup","photo","commons"],
    orientation: "landscape",
    focus: "center",
  },
  {
    id: "uruguay-argentina-final-0a3cccbc",
    src: "/daily-images/commons/uruguay-argentina-final-0a3cccbc.jpg",
    title: "1930: Uruguay argentina finale",
    alt: "Arkivbilde fra 1930: Uruguay argentina final",
    caption: "Arkivbilde fra 1930-sporet i VM-arkivet: Uruguay argentina final.",
    context: "Den første VM-finalen gjør arkivet fysisk: korte bukser, lang reise og et mesterskap som ennå ikke visste at det skulle bli en verdenskalender.",
    facts: ["Uruguay slo Argentina 4-2 i finalen.","Finalen ble spilt på Estadio Centenario i Montevideo.","1930-VM hadde bare 13 lag."],
    credit: "Unknown author",
    license: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Uruguay%20argentina%20final.jpg",
    approved: true,
    mediaType: "photo",
    year: "1930",
    teams: ["Uruguay","Argentina"],
    matchIds: [],
    momentIds: ["uruguay-1930"],
    tags: ["1930","final","uruguay","argentina","rimet","early-world-cup","photo","commons"],
    orientation: "landscape",
    focus: "center",
  }
];
